const app=document.getElementById('app');
const requested=Number(new URLSearchParams(location.search).get('d')||25);
const designNo=Math.max(25,Math.min(60,requested));
const idx=designNo-25;

const roles=[
  {key:'general',name:'일반용',en:'GENERAL',icon:'wrench',color:'#008b78',process:'PRESS 일반용',desc:'정기 작업자 인증'},
  {key:'electrical',name:'전장용',en:'ELECTRICAL',icon:'cpu',color:'#2565d0',process:'PRESS 전장용',desc:'VDA 포함 전장 인증'},
  {key:'newcomer',name:'신입용',en:'NEWCOMER',icon:'graduation-cap',color:'#5c9631',process:'수직흑화 신입용',desc:'신규 작업자 교육'},
  {key:'foreign',name:'외국인용',en:'GLOBAL',icon:'languages',color:'#c94b69',process:'PRESS 외국인용',desc:'다국어 작업자 인증'}
];
const selected=roles[idx%roles.length];
const themes=[
  ['#f3f5f5','#fff','#e7ecee','#d6dde0','#172126','#68787e','#b5c0c4','#087f6b','#1d62aa','#d59b1d','#c54a45'],
  ['#f6f1eb','#fff','#eee5db','#ddd3c8','#251f1b','#746a62','#c7bab0','#b44e32','#275e8f','#d29d23','#b63f3d'],
  ['#edf3f5','#fff','#e2ebee','#cad6da','#102b38','#667c85','#adc0c7','#007d78','#2d68bb','#d4a522','#c94c4c'],
  ['#f1f3ee','#fff','#e4e9df','#d1d8cd','#263126','#6e796d','#b8c2b5','#4f7f36','#275f9f','#d4a21f','#bc4e46'],
  ['#f3f1f5','#fff','#e7e1eb','#d5ced9','#2d2330','#756b79','#c1b6c5','#8b4d78','#356ba4','#d09b28','#bf4d4b'],
  ['#edf1f2','#fff','#dfe6e8','#cbd4d7','#17262c','#67787f','#acbabf','#d05b36','#126398','#d5a21e','#c44945']
];
const t=themes[idx%themes.length];
const themeKeys=['--bg','--surface','--soft','--stage','--ink','--muted','--line','--accent','--accent2','--warn','--danger'];
const concepts=[
  ['공공서비스 시작','공공'],['완료해야 할 세 가지','공공'],['의료 체크인','의료'],['안전 확인 먼저','의료'],
  ['Fluent Windows 홈','Windows'],['빠른 명령 검색','Windows'],['Carbon 데이터 작업대','업무'],['Carbon 안내 입력','업무'],
  ['산업 오퍼레이터 스테이션','산업'],['공장 라인 지도','산업'],['SAP 업무 타일','업무'],['SAP 공간과 페이지','업무'],
  ['단계 표시 서비스','접근성'],['고대비 쉬운 선택','접근성'],['명찰 스캔 시작','키오스크'],['공항 여정 표시','키오스크'],
  ['승차권 발매기형','키오스크'],['도서관 셀프대출형','키오스크'],['POS 빠른 선택','현장'],['ATM 단계 선택','키오스크'],
  ['여권 심사형','글로벌'],['작업자 명단형','관리'],['교실 칠판형','교육'],['인증 카드 지갑','교육'],
  ['사원증 태그 시작','스캔'],['QR 공정 스캔','스캔'],['즐겨찾기 홈','개인화'],['최근 시험 타임라인','개인화'],
  ['공정 배치도','산업'],['품질 Andon','산업'],['교대 인수인계','현장'],['주간 시험 일정','일정'],
  ['전체 종이 미리보기','문서'],['두 문서 비교','문서'],['하단 도크 작업대','Windows'],['한 번에 질문 하나','초간단']
];
const viewNames=['gov','task','nhs','clinical','fluent-home','command','carbon-data','carbon-form','ix-station','ix-plant','fiori','spaces','us-step','high','scan','journey','ticket','library','pos','atm','passport','roster','classboard','wallet','badge','qr','favorites','timeline','map','andon','handover','calendar','fullprint','compare','dock','oneq'];

function I(name,size=''){return `<i data-lucide="${name}" class="icon ${size}"></i>`}
function B(label,icon='arrow-right',cls=''){return `<button class="btn ${cls}">${I(icon)}<span>${label}</span></button>`}
function brand(label='OJT EXAM MAKER'){return `<div class="brand"><span class="brand-mark">${I('badge-check')}</span><span><b>${label}</b><small>QUALITY TRAINING SYSTEM</small></span></div>`}
function heading(kicker,title,copy='',level='h2'){return `<div class="heading"><span class="eyebrow">${kicker}</span><${level}>${title}</${level}>${copy?`<p>${copy}</p>`:''}</div>`}
function roleStyle(r){return `--role:${r.color}`}
function rolePills(){return `<div class="role-pills">${roles.map(r=>`<button class="role-pill ${r.key===selected.key?'active':''}" style="${roleStyle(r)}"><span class="role-dot"></span>${r.name}</button>`).join('')}</div>`}
function roleCards(){return `<div class="role-grid">${roles.map(r=>`<article class="role-card ${r.key===selected.key?'active':''}" style="${roleStyle(r)}">${I(r.icon,'lg')}<h3>${r.name}</h3><p>${r.desc}</p></article>`).join('')}</div>`}
function field(label,value,icon='chevron-down'){return `<div class="field"><label>${label}</label><div class="control"><span>${value}</span><span class="grow"></span>${I(icon,'sm')}</div></div>`}
function identity(){return `<div class="identity">${field('성명','오국진','user-round')}${field('평가 일시','2026.08.06','calendar-days')}</div>`}
function checks(count=4){const list=[['최신 문제은행','방금 자동으로 확인'],['시험 대상','일반·전장·신입·외국인'],['공정 선택',selected.process],['작업자','오국진'],['출력 문서','문제 + 답안'],['목표 점수','100점']];return `<div class="check-list">${list.slice(0,count).map((x,i)=>`<div class="check"><span class="check-mark">${i+1}</span><div><b>${x[0]}</b><small>${x[1]}</small></div><em>완료</em></div>`).join('')}</div>`}
function processRows(count=8){const names=['PRESS 일반용','PRESS 전장용','TRIM 일반용','TRIM 전장용','X-Ray 일반용','X-Ray 전장용','수직흑화 신입용','출하검사 일반용','노바본드 전장용','액분석 일반용'];return `<div class="process-list">${names.slice(0,count).map((name,i)=>`<div class="process-row ${i===idx%Math.min(count,4)?'active':''}"><span>${i+1}</span><div><b>${name}</b><small>${i%2?'전장 작업자 인증':'정기 작업자 인증'}</small></div><em>${i===idx%Math.min(count,4)?'선택됨':'열기'}</em></div>`).join('')}</div>`}
function metrics(){return `<div class="metric-grid"><div class="metric"><span>문제</span><b>24</b></div><div class="metric"><span>총점</span><b>100</b></div><div class="metric"><span>페이지</span><b>5</b></div></div>`}
function topbar(label='OJT EXAM MAKER'){return `<header class="top">${brand(label)}<span class="grow"></span>${rolePills()}${B('관리자','lock-keyhole','secondary')}</header>`}
function paper(){const qs=['작업표준서와 실제 작업 방법이 다를 때 가장 적절한 조치는?','설비 점검 주기가 지났으나 생산 일정이 촉박하다. 어떻게 해야 하는가?','제품 표면의 상태를 올바르게 판정한 것은?','현장 작업 중 이상 상태를 발견했을 때 가장 먼저 할 행동은?','최종 수세단 필터 교체 주기로 맞는 것은?'];return `<div class="paper"><div class="paper-head"><div class="paper-box"><span>부서명</span><span>가공팀</span><span>평가자</span><span>오국진</span><span>평가 일시</span><span>2026.08.06</span></div><div class="paper-title">교육 평가서</div><div class="approval"><span>기안</span><span>심의</span><span>결정</span><span></span><span></span><span></span><span>/</span><span>/</span><span>/</span></div></div><div class="paper-info"><span>직무명</span><span>${selected.process}</span><span>성명</span><span>오국진</span><span>평가 방법</span><span style="grid-column:2/5">시험 평가, 결과 보고서, 직무 평가</span><span>개정 차수</span><span>1</span><span>제정일</span><span>2026.08.06</span></div><div class="paper-qs">${qs.map((q,i)=>`<div class="paper-q"><b>${i+1}.</b><span>${q}</span><b>(${i<2?'2.5':'4'}점)</b><small>① 작업 중지　② 관리자 보고　③ 상태 기록　④ 기준 확인</small></div>`).join('')}</div><div class="paper-foot"><span>JIQP-0202-02</span><span>( 주 ) 지 인</span><span>A4(210*297)mm</span></div></div>`}
function nav(items,active=0){return items.map((x,i)=>`<div class="nav-item ${i===active?'active':''}">${I(x[0])}<span>${x[1]}</span></div>`).join('')}

const builders=[
  () => `<header class="gov-head">${brand('OJT 시험 서비스')}<span class="grow"></span><span>문제은행 연결 완료</span></header><main class="gov-main"><section><span class="eyebrow">작업자 인증</span><h1>${selected.process}<br>시험을 시작합니다</h1><p>시험 대상과 작업자 정보를 확인한 뒤 시작하세요. 시험이 끝나면 문제지와 답안지가 함께 출력됩니다.</p><div class="gov-list"><span>${I('check-circle-2')}성명과 평가 일시 확인</span><span>${I('check-circle-2')}최신 문제은행 자동 반영</span><span>${I('check-circle-2')}출력 문서 5페이지</span></div>${B('시험 시작','arrow-right','huge')}</section><aside class="gov-side"><h3>시험 대상</h3>${roles.map(r=>`<div class="process-row ${r.key===selected.key?'active':''}" style="${roleStyle(r)}"><span>${I(r.icon,'sm')}</span><div><b>${r.name}</b><small>${r.desc}</small></div></div>`).join('')}</aside></main><footer class="gov-foot"><b>OJT 작업자 인증 시험</b><span class="grow"></span><span>관리자 설정은 비밀번호로 보호됩니다.</span></footer>`,

  () => `${topbar('OJT TASKS')}<main class="task-layout"><section class="task-main">${heading('시작 전 확인','완료해야 할 세 가지','세 항목을 모두 확인하면 시험을 시작할 수 있습니다.','h1')}<div class="task-list">${[['users-round','시험 대상 선택',selected.name],['factory','공정 선택',selected.process],['user-round','작업자 확인','오국진 · 2026.08.06']].map((x,i)=>`<div class="task-row"><span class="num">${i+1}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div><span class="task-tag">완료</span></div>`).join('')}</div></section><aside class="task-side">${heading('READY','시험 준비 완료','모든 필수 항목을 확인했습니다.')}<div>${checks(5)}</div>${B('시험 시작','play','big')}</aside></main>`,

  () => `<header class="nhs-head">${brand('OJT TRAINING')}<span class="grow"></span><span>작업자 인증 서비스</span></header><main class="nhs-main"><section class="nhs-copy"><span class="eyebrow">시험 시작</span><h1>${selected.process}</h1><p>이 서비스는 작업자가 공정 기준을 정확히 이해했는지 확인합니다.</p><div class="nhs-callout"><b>시작하기 전에</b><br>성명과 시험 일자를 확인하고, 선택한 공정이 맞는지 확인하세요.</div><h2>시험을 완료하면</h2><p>문제지와 답안지가 함께 출력되며, 관리자가 채점할 수 있습니다.</p>${B('지금 시작','play','huge')}</section><aside class="nhs-panel">${heading('YOUR EXAM','시험 정보',selected.desc)}<div style="margin-top:20px">${identity()}</div><div style="margin-top:18px">${metrics()}</div><div style="margin-top:18px">${rolePills()}</div></aside></main>`,

  () => `<header class="clinical-head">${brand('OJT SAFETY CHECK')}<span class="grow"></span><span class="status" style="color:#7de0d2">SYSTEM READY</span>${B('관리자','lock-keyhole','secondary')}</header><main class="clinical-body"><aside class="clinical-left">${heading('01','시험 대상',selected.name)}<div>${roleCards()}</div>${B('대상 확인','check','secondary')}</aside><section class="clinical-center">${heading('SAFETY GATE','안전 확인 먼저','시험을 시작하기 전에 아래 항목을 확인합니다.')}<div class="safety-gate">${[['shield-check','문제은행 최신 상태'],['factory','공정 선택 확인'],['user-check','작업자 본인 확인'],['printer-check','출력 문서 준비']].map(x=>`<div class="safety-item done">${I(x[0],'lg')}<div><b>${x[1]}</b><p style="margin:5px 0 0;color:#6e7c79;font-size:9px">정상 확인됨</p></div></div>`).join('')}</div><span class="status">모든 안전 확인 완료</span></section><aside class="clinical-right">${heading('02','작업자 정보',selected.process)}<div>${identity()}<div style="margin-top:14px">${metrics()}</div></div>${B('시험 시작','play','big')}</aside></main>`,

  () => `<aside class="fluent-rail"><div class="brand-mark">${I('badge-check')}</div>${[['home','홈'],['play','시험'],['file-text','문서'],['history','기록'],['settings','설정']].map((x,i)=>`<button class="rail-btn ${i===1?'active':''}" title="${x[1]}">${I(x[0])}</button>`).join('')}<span class="grow"></span><button class="rail-btn">${I('log-out')}</button></aside><main class="fluent-main"><header style="display:flex;align-items:center">${heading('GOOD MORNING','오국진 님','오늘 인증 시험을 준비합니다.')}<span class="grow"></span>${rolePills()}</header><section class="welcome-strip"><div>${heading('CURRENT EXAM',selected.process,selected.desc)}</div><span class="grow"></span><span class="status">준비 완료</span>${B('시작','play','big')}</section><section class="fluent-grid"><article class="fluent-card"><h3>시험 대상</h3>${roleCards()}</article><article class="fluent-card"><h3>작업자 정보</h3><div style="margin-top:16px">${identity()}</div><div style="margin-top:16px">${checks(4)}</div></article><article class="fluent-card accent"><span class="eyebrow" style="color:#9fc9ff">DOCUMENT</span><h2>출력 문서</h2><p>문제 4페이지<br>답안 1페이지</p><div style="margin-top:22px">${metrics()}</div></article></section><footer class="fluent-footer"><span class="status">문제은행 자동 갱신</span><span class="grow"></span>${B('출력 미리보기','scan-search','secondary')}${B('관리자','lock-keyhole','secondary')}</footer></main>`,

  () => `<div class="command-backdrop"><div class="ghost-panel"></div><div class="ghost-panel"></div><div class="ghost-panel"></div></div><section class="command-box"><div class="command-search">${I('search','lg')}<input value="PRESS" aria-label="공정 검색"><span class="status">8개 결과</span></div><div class="command-results">${['PRESS 일반용','PRESS 전장용','TRIM 일반용','X-Ray 전장용','최근 시험 열기','출력 미리보기'].map((x,i)=>`<div class="command-result ${i===idx%4?'active':''}"><span>${I(i<4?'factory':i===4?'history':'printer')}</span><div><b>${x}</b><small>${i<4?'시험 공정':'빠른 명령'}</small></div><span>${i<4?'Enter':'Ctrl + '+(i+1)}</span></div>`).join('')}</div></section>`,

  () => `<header class="carbon-head">${brand('OJT DATA WORKSPACE')}<span class="grow"></span><span>오국진</span>${B('관리자','lock-keyhole','dark')}</header><main class="carbon-body"><aside class="carbon-nav">${nav([['dashboard','대시보드'],['play','시험 실행'],['database','문제은행'],['file-text','출력 문서'],['history','시험 기록'],['settings','설정']],1)}</aside><section class="carbon-main"><div>${heading('EXAM RUN','공정 시험 실행','데이터를 확인하고 선택한 시험을 시작합니다.')}</div><div class="carbon-table"><div class="carbon-row head"><span>NO</span><span>공정명</span><span>대상</span><span>상태</span></div>${['PRESS 일반용','PRESS 전장용','TRIM 일반용','TRIM 전장용','X-Ray 일반용','수직흑화 신입용','출하검사 일반용','노바본드 전장용','액분석 일반용'].map((x,i)=>`<div class="carbon-row ${i===idx%4?'active':''}"><span>${String(i+1).padStart(2,'0')}</span><b>${x}</b><span>${roles[i%4].name}</span><span>${i===idx%4?'선택됨':'사용 가능'}</span></div>`).join('')}</div></section><aside class="carbon-side">${heading('SELECTED',selected.process,selected.desc)}<div>${metrics()}<div style="margin-top:16px">${identity()}</div><div style="margin-top:16px">${checks(4)}</div></div>${B('시험 시작','play','big')}</aside></main>`,

  () => `<header class="carbon-head">${brand('OJT GUIDED SETUP')}<span class="grow"></span><span class="status">자동 저장</span></header><main class="form-shell"><aside class="form-steps">${[['users-round','시험 대상'],['factory','공정'],['user-round','작업자'],['check-circle-2','확인']].map((x,i)=>`<div class="form-step ${i===1?'active':''}">${I(x[0])}<div><b>${i+1}. ${x[1]}</b><small style="display:block;margin-top:4px;color:#6d7a80">${i<1?'완료':i===1?'현재 단계':'대기'}</small></div></div>`).join('')}</aside><section class="form-center">${heading('STEP 2 OF 4','공정을 선택하세요','시험을 볼 공정 하나를 선택합니다.','h1')}<div class="form-block">${field('공정 검색','PRESS','search')}${processRows(6)}</div><div style="margin-top:24px;display:flex;gap:10px">${B('이전','arrow-left','secondary')}${B('계속','arrow-right','big')}</div></section><aside class="form-summary">${heading('SUMMARY','현재 선택',selected.name)}<div>${rolePills()}<div style="margin-top:18px">${metrics()}</div></div>${B('나중에 계속','save','secondary')}</aside></main>`,

  () => `<header class="ix-head">${brand('OJT OPERATOR STATION')}<span class="grow"></span><span class="status">ONLINE</span>${B('관리자','lock-keyhole','dark')}</header><section class="ix-status"><div class="ix-stat"><span>문제은행</span><b>최신</b></div><div class="ix-stat"><span>프린터</span><b>준비</b></div><div class="ix-stat"><span>시험 대상</span><b>${selected.name}</b></div><div class="ix-stat"><span>작업자</span><b>오국진</b></div><div class="ix-stat"><span>총점</span><b>100점</b></div></section><main class="ix-grid">${roles.map(r=>`<article class="ix-tile ${r.key===selected.key?'active':''}" style="${roleStyle(r)}"><div>${I(r.icon,'xl')}</div><div><span>${r.en}</span><h2>${r.name}</h2><p>${r.process}<br>${r.desc}</p></div><div style="display:flex;align-items:center"><span>${r.key===selected.key?'SELECTED':'OPEN'}</span><span class="grow"></span>${I('arrow-right','lg')}</div></article>`).join('')}</main>`,

  () => `<header class="plant-head">${brand('OJT PLANT OVERVIEW')}<span class="grow"></span><span class="status">4 LINES READY</span></header><main class="plant-body"><section class="floor-map"><div class="map-line" style="left:60px;top:70px;width:260px"><h3>PRESS LINE</h3><p>일반용 · 전장용</p></div><div class="map-line active" style="left:420px;top:210px;width:300px"><h3>${selected.process}</h3><p>시험 준비 완료 · 오국진</p></div><div class="map-line" style="left:820px;top:80px;width:250px"><h3>TRIM LINE</h3><p>일반용 · 전장용</p></div><div class="map-line" style="left:900px;top:440px;width:260px"><h3>X-RAY LINE</h3><p>일반용 · 전장용</p></div><div class="map-line" style="left:180px;top:500px;width:280px"><h3>TRAINING ZONE</h3><p>신입용 · 외국인용</p></div></section><aside class="plant-side">${heading('SELECTED LINE',selected.process,selected.desc)}<div>${checks(5)}</div>${B('시험 시작','play','big')}</aside></main><footer class="plant-foot"><span class="status">문제은행 최신</span><span class="grow"></span>${B('공정 목록','rows-3','dark')}${B('출력 미리보기','printer','dark')}</footer>`,

  () => `<header class="fiori-head">${brand('OJT LAUNCHPAD')}<span class="grow"></span>${I('search')}${I('bell')}<span>오국진</span></header><main class="fiori-body"><section class="fiori-hero"><div>${heading('MY WORK','오늘의 작업자 인증','자주 사용하는 시험을 한 번에 실행합니다.')}</div><span class="grow"></span><span class="status" style="color:#fff">READY</span></section><section class="fiori-launch">${roles.map(r=>`<article class="fiori-tile ${r.key===selected.key?'active':''}" style="${roleStyle(r)}"><div>${I(r.icon,'lg')}</div><div><h3>${r.name}</h3><p>${r.desc}</p></div><div style="display:flex;align-items:center"><b>${r.process}</b><span class="grow"></span>${I('arrow-right')}</div></article>`).join('')}</section><section class="fiori-launch" style="grid-template-columns:repeat(3,1fr)"><article class="fiori-tile"><div>${I('history')}</div><h3>최근 시험</h3><p>마지막 실행 공정을 다시 엽니다.</p></article><article class="fiori-tile"><div>${I('files')}</div><h3>출력 문서</h3><p>문제지와 답안지를 확인합니다.</p></article><article class="fiori-tile"><div>${I('settings')}</div><h3>관리자 설정</h3><p>비밀번호가 필요합니다.</p></article></section></main>`,

  () => `<aside class="spaces-nav">${brand('OJT SPACES')}${nav([['home','내 홈'],['play','시험 실행'],['graduation-cap','신입 교육'],['languages','외국인 시험'],['file-text','출력 문서'],['settings','관리자']],1)}</aside><main class="spaces-main"><header style="display:flex;align-items:center">${heading('SPACE','작업자 시험','업무별로 필요한 기능만 모았습니다.')}<span class="grow"></span>${B('검색','search','secondary')}</header><section><div class="space-group"><h3>시험 시작</h3><div class="space-apps">${roles.slice(0,3).map(r=>`<div class="space-app ${r.key===selected.key?'active':''}">${I(r.icon,'lg')}<div><b>${r.name}</b><p style="margin:4px 0 0;color:#6e7b80;font-size:8px">${r.process}</p></div><span class="grow"></span>${I('arrow-right')}</div>`).join('')}</div></div><div class="space-group"><h3>문서와 기록</h3><div class="space-apps"><div class="space-app">${I('printer','lg')}<b>출력 미리보기</b></div><div class="space-app">${I('history','lg')}<b>최근 시험</b></div><div class="space-app">${I('database','lg')}<b>문제은행 상태</b></div></div></div><div class="space-group"><h3>관리</h3><div class="space-apps"><div class="space-app">${I('lock-keyhole','lg')}<b>관리자 설정</b></div></div></div></section></main>`,

  () => `<header class="us-head">${brand('OJT CERTIFICATION SERVICE')}<span class="grow"></span><span class="status">문제은행 연결</span></header><section class="step-indicator">${['시험 대상','공정 선택','작업자 확인','시험 시작'].map((x,i)=>`<div class="step-segment ${i<1?'done':i===1?'active':''}">${i+1}. ${x}</div>`).join('')}</section><main class="us-body"><section class="us-main">${heading('STEP 2','어느 공정 시험을 볼까요?','하나를 선택한 뒤 다음으로 이동하세요.','h1')}<div class="us-options">${['PRESS 일반용','PRESS 전장용','TRIM 일반용','X-Ray 전장용'].map((x,i)=>`<div class="us-option ${i===idx%4?'active':''}"><span>${I('factory','lg')}</span><div><b>${x}</b><p style="margin:5px 0 0;color:#64757c;font-size:8px">작업자 인증 시험</p></div></div>`).join('')}</div><div style="margin-top:24px;display:flex;gap:10px">${B('뒤로','arrow-left','secondary')}${B('다음','arrow-right','big')}</div></section><aside class="us-side">${heading('YOUR PROGRESS','현재 선택',selected.name)}<div style="margin-top:18px">${checks(4)}</div></aside></main>`,

  () => `<header class="high-head">${brand('OJT EASY MODE')}<span class="grow"></span><span>고대비 화면</span></header><section class="high-title"><div><span style="color:#ffdd00;font-weight:900">1 / 3</span><h1>누가 시험을 보나요?</h1></div></section><main class="high-grid">${roles.map((r,i)=>`<article class="high-choice ${r.key===selected.key?'active':''}"><span class="big-letter">${String.fromCharCode(65+i)}</span><div><h2>${r.name}</h2><p>${r.desc}</p></div>${I('arrow-right','lg')}</article>`).join('')}</main>`,

  () => `${topbar('OJT SCAN START')}<main class="scan-main"><section class="scan-stage"><div class="scan-box">${I('scan-line','xl')}<h1>사원증을 스캔하세요</h1><p>스캔하면 작업자와 예정 시험을 자동으로 불러옵니다.</p><span class="status">스캐너 준비</span></div></section><aside class="scan-side">${heading('MANUAL START','직접 선택하기','사원증이 없으면 아래에서 선택하세요.')}<div>${rolePills()}<div style="margin-top:18px">${processRows(6)}</div></div>${B('직접 시작','play','secondary')}</aside></main><footer class="scan-foot"><span class="status">문제은행 최신</span><span class="grow"></span>${B('관리자','lock-keyhole','secondary')}</footer>`,

  () => `<header class="journey-head">${brand('OJT CHECK-IN JOURNEY')}<span class="grow"></span><span>오국진 · 2026.08.06</span></header><section class="journey-strip">${[['languages','언어'],['users-round','대상'],['factory','공정'],['user-round','작업자'],['play','시작']].map((x,i)=>`<div class="journey-step ${i<3?'done':i===3?'active':''}">${I(x[0])}<div><b>${i+1}. ${x[1]}</b></div><span>${i<3?'완료':i===3?'현재':'대기'}</span></div>`).join('')}</section><main class="journey-main"><section class="journey-focus">${I('user-check','xl')}<span class="eyebrow">STEP 4</span><h1>작업자 정보를<br>확인하세요</h1><div style="width:520px;margin-top:18px">${identity()}</div></section><aside class="journey-side">${heading('BOARDING PASS',selected.process,selected.name)}<div>${checks(5)}</div>${B('확인하고 계속','arrow-right','big')}</aside></main>`,

  () => `<main class="ticket-shell"><header class="ticket-head">${brand('OJT SELF SERVICE')}<span class="grow"></span><b>시험 대상을 선택하세요</b></header><section class="ticket-grid">${roles.map((r,i)=>`<article class="ticket-choice ${r.key===selected.key?'active':''}" style="${roleStyle(r)}"><span>${I(r.icon,'xl')}</span><div><h2>${r.name}</h2><p>${r.en}<br>${r.desc}</p></div><span style="font-size:28px;font-weight:900">0${i+1}</span></article>`).join('')}</section><footer class="ticket-foot"><span>${I('volume-2')} 음성 안내</span><span class="grow"></span><span>화면을 눌러 선택하세요</span></footer></main>`,

  () => `<aside class="library-scan">${brand('OJT SELF CHECK')}<h1>작업자 번호를<br>스캔하세요</h1><div class="library-slot">${I('scan-barcode','xl')}<b>SCAN HERE</b></div><p>사원증 또는 작업자 QR을 스캔하면<br>시험 목록이 자동으로 나타납니다.</p><span class="status" style="color:#fff">READER READY</span></aside><main class="library-main"><header style="display:flex;align-items:center">${heading('AVAILABLE','응시 가능한 시험','오국진 님에게 배정된 시험입니다.')}<span class="grow"></span>${B('직접 검색','search','secondary')}</header><section class="library-list">${['PRESS 일반용','TRIM 일반용','수직흑화 신입용','X-Ray 전장용','출하검사 일반용','노바본드 전장용'].map((x,i)=>`<div class="library-row ${i===idx%4?'active':''}"><span>${I('file-check-2','lg')}</span><div><b>${x}</b><p style="margin:4px 0 0;color:#6c7b80;font-size:8px">작업자 인증 · 100점</p></div><span>${i===idx%4?'선택됨':'열기'}</span></div>`).join('')}</section><footer class="library-actions"><span class="status">문제은행 최신</span><span class="grow"></span>${B('시험 시작','play','big')}</footer></main>`,

  () => `<aside class="pos-cat">${brand('OJT QUICK POS')}<div style="margin-top:24px">${nav([['star','즐겨찾기'],['wrench','일반용'],['cpu','전장용'],['graduation-cap','신입용'],['languages','외국인용'],['history','최근 시험']],idx%5)}</div></aside><main class="pos-main"><header style="display:flex;align-items:center">${heading('QUICK SELECT','시험 공정','자주 사용하는 공정을 바로 선택합니다.')}<span class="grow"></span>${B('검색','search','secondary')}</header><section class="pos-grid">${['PRESS 일반용','PRESS 전장용','TRIM 일반용','TRIM 전장용','X-Ray 일반용','X-Ray 전장용','출하검사 일반용','수직흑화 신입용','노바본드 전장용'].map((x,i)=>`<article class="pos-item ${i===idx%6?'active':''}"><span>${I('factory','lg')}</span><div><h3>${x}</h3><p style="color:#6d7a80;font-size:8px">작업자 인증</p></div><span class="score">100</span></article>`).join('')}</section></main><aside class="pos-cart">${heading('SELECTED','선택한 시험',selected.process)}<div>${identity()}<div style="margin-top:16px">${checks(4)}</div></div><div><div class="cart-total"><span>총점</span><b>100점</b></div><div style="margin-top:12px">${B('시험 시작','play','big')}</div></div></aside>`,

  () => `<main class="atm-shell"><section class="atm-main">${heading('STEP 1 OF 3','시험 대상을 선택하세요','화면 오른쪽 버튼이나 목록을 눌러 선택합니다.','h1')}<div class="atm-options">${roles.map((r,i)=>`<div class="atm-option ${r.key===selected.key?'active':''}"><span style="font-size:21px;font-weight:900">${i+1}</span>${I(r.icon,'lg')}<b>${r.name}</b><span class="grow"></span><span>${r.en}</span></div>`).join('')}</div><div style="display:flex;gap:12px"><span class="status">화면 터치 가능</span><span class="grow"></span>${B('취소','x','secondary')}${B('다음','arrow-right','big')}</div></section><aside class="atm-keypad">${[1,2,3,4,5,6,7,8,9,'←',0,'확인'].map(x=>`<div class="key">${x}</div>`).join('')}</aside></main>`,

  () => `<header class="passport-head">${brand('OJT IDENTITY CHECK')}<span class="grow"></span>${rolePills()}</header><main class="passport-body"><section class="passport-card"><span class="eyebrow" style="color:#9bc8df">WORKER CREDENTIAL</span><div class="passport-grid"><div class="passport-photo">${I('user-round','xl')}</div><div class="passport-data"><div><span>NAME</span><b>오국진</b></div><div><span>DEPARTMENT</span><b>품질관리팀</b></div><div><span>EXAM DATE</span><b>2026.08.06</b></div><div><span>STATUS</span><b>VERIFIED</b></div></div></div><div style="margin-top:34px">${metrics()}</div></section><section class="passport-main">${heading('SELECT EXAM','시험을 선택하세요','작업자 인증 정보와 연결됩니다.','h1')}<div class="passport-actions">${roles.map(r=>`<article class="passport-action ${r.key===selected.key?'active':''}">${I(r.icon,'lg')}<h3>${r.name}</h3><p>${r.process}</p></article>`).join('')}</div><div style="display:flex;gap:10px"><span class="status">본인 확인 완료</span><span class="grow"></span>${B('시험 시작','play','big')}</div></section></main>`,

  () => `<header style="display:flex;align-items:center">${brand('OJT WORKER ROSTER')}<span class="grow"></span>${field('작업자 검색','오국진','search')}${B('관리자','lock-keyhole','secondary')}</header><main class="roster-main"><section class="roster-table"><div class="roster-row head"><span>NO</span><span>작업자</span><span>예정 시험</span><span>상태</span></div>${['김유준','박지영','오국진','이형건','최현석','응우옌 반안','쩐 티 흐엉','정미라','권성민','이승호','한도윤','윤서준'].map((x,i)=>`<div class="roster-row ${i===2?'active':''}"><span>${String(i+1).padStart(2,'0')}</span><b>${x}</b><span>${['PRESS 일반용','TRIM 전장용','X-Ray 일반용'][i%3]}</span><span>${i===2?'선택됨':'대기'}</span></div>`).join('')}</section><aside class="roster-side">${heading('WORKER','오국진',selected.process)}<div>${identity()}<div style="margin-top:16px">${checks(4)}</div></div>${B('시험 시작','play','big')}</aside></main><footer class="roster-foot"><span class="status">12명 예정</span><span class="grow"></span>${B('오늘 일정','calendar-days','secondary')}</footer>`,

  () => `<header class="class-head">${brand('OJT CLASSROOM')}<span class="grow"></span><span>오늘의 인증 시험</span></header><main class="class-board"><span style="color:#f3dc67">QUESTION 1</span><h1>어떤 시험을 준비할까요?</h1><section class="class-grid">${roles.map((r,i)=>`<article class="class-card ${r.key===selected.key?'active':''}"><span style="font-size:32px;font-weight:900">${String.fromCharCode(65+i)}</span><h2>${r.name}</h2><p>${r.en}<br>${r.desc}</p>${I(r.icon,'lg')}</article>`).join('')}</section></main><footer class="class-foot"><span>${I('mouse-pointer-click')} 화면을 눌러 선택하세요</span><span class="grow"></span>${B('다음 문제','arrow-right','secondary')}</footer>`,

  () => `<header class="wallet-head">${brand('OJT CERTIFICATE WALLET')}<span class="grow"></span>${B('작업자 변경','users-round','secondary')}</header><main class="wallet-body"><section class="wallet-main">${heading('MY CERTIFICATIONS','오국진 님의 인증 카드','시험을 볼 카드를 선택하세요.')}<div class="wallet-cards">${roles.map(r=>`<article class="credential ${r.key===selected.key?'active':''}"><div style="display:flex;align-items:center">${I(r.icon,'lg')}<span class="grow"></span><span>${r.en}</span></div><div><h2>${r.name}</h2><p>${r.process}<br>VALID 2026</p></div><div style="display:flex"><b>100 POINTS</b><span class="grow"></span>${I('arrow-right')}</div></article>`).join('')}</div></section><aside class="wallet-side">${heading('SELECTED CARD',selected.name,selected.process)}<div>${identity()}<div style="margin-top:16px">${checks(4)}</div></div>${B('시험 시작','play','big')}</aside></main>`,

  () => `<main class="badge-stage"><section class="badge-reader"><div class="badge-icon">${I('contactless','xl')}</div><span class="eyebrow">TOUCH YOUR BADGE</span><h1>사원증을 태그하세요</h1><p>작업자와 예정 시험을 자동으로 확인합니다.</p><span class="status">리더기 준비</span></section></main><aside class="badge-side">${brand('OJT BADGE START')}<div>${heading('FAST START','태그 한 번으로 시작','사원증이 확인되면 시험 정보가 자동으로 열립니다.')}<div style="margin-top:26px">${checks(5)}</div></div>${B('직접 입력','keyboard','secondary')}</aside>`,

  () => `<header style="display:flex;align-items:center">${brand('OJT QR START')}<span class="grow"></span><span class="status">CAMERA READY</span>${B('관리자','lock-keyhole','secondary')}</header><main class="qr-body"><section class="qr-camera"><div class="qr-frame"></div><h2>공정 QR을 비추세요</h2><p>공정과 시험 유형을 자동으로 불러옵니다.</p></section><section class="qr-result">${heading('SCAN RESULT','PRESS 일반용','공정 QR을 인식했습니다.','h1')}<div>${metrics()}<div style="margin-top:20px">${identity()}</div><div style="margin-top:20px">${checks(4)}</div></div><div style="display:flex;gap:10px"><span class="status">인식 완료</span><span class="grow"></span>${B('다시 스캔','scan-line','secondary')}${B('시험 시작','play','big')}</div></section></main><footer class="qr-foot"><span>QR이 없으면 공정명을 직접 검색할 수 있습니다.</span><span class="grow"></span>${B('직접 검색','search','secondary')}</footer>`,

  () => `<header class="wallet-head">${brand('OJT MY HOME')}<span class="grow"></span>${rolePills()}${B('관리자','lock-keyhole','secondary')}</header><section class="favorite-strip">${roles.map(r=>`<article class="favorite ${r.key===selected.key?'active':''}">${I(r.icon,'lg')}<div><h3>${r.process}</h3><p>${r.desc}</p></div>${I('star')}</article>`).join('')}</section><main class="recent-layout"><section class="recent-main">${heading('RECENT','최근 실행한 시험','마지막 작업 순서대로 표시합니다.')}<div style="margin-top:18px">${processRows(8)}</div></section><aside class="recent-side">${heading('QUICK START',selected.process,'즐겨찾기 시험')}<div>${identity()}<div style="margin-top:16px">${checks(4)}</div></div>${B('바로 시작','play','big')}</aside></main>`,

  () => `<header style="display:flex;align-items:center">${brand('OJT ACTIVITY')}<span class="grow"></span>${B('오늘','calendar-days','secondary')}${B('관리자','lock-keyhole','secondary')}</header><main class="timeline-body"><section class="timeline">${[['08:30','PRESS 일반용','완료'],['10:00',selected.process,'현재'],['13:30','TRIM 전장용','예정'],['15:00','수직흑화 신입용','예정'],['16:30','출하검사 일반용','예정']].map((x,i)=>`<div class="time-item"><span class="time-dot">${x[0]}</span><article class="time-card ${i===1?'active':''}"><div style="display:flex"><div><b>${x[1]}</b><p style="margin:5px 0 0;color:#6d7b80;font-size:8px">작업자 인증 시험</p></div><span class="grow"></span><span class="status">${x[2]}</span></div></article></div>`).join('')}</section><aside class="timeline-side">${heading('NOW','현재 시험',selected.process)}<div>${identity()}<div style="margin-top:18px">${checks(4)}</div></div>${B('시험 시작','play','big')}</aside></main>`,

  () => `<header style="display:flex;align-items:center">${brand('OJT PROCESS MAP')}<span class="grow"></span>${rolePills()}${B('목록 보기','rows-3','secondary')}</header><main class="process-map"><div class="map-road" style="left:220px;top:205px;width:900px"></div><div class="map-road" style="left:670px;top:205px;width:14px;height:430px"></div>${[['PRESS','왼쪽 상단',140,120],['TRIM','중앙 상단',540,120],['X-RAY','오른쪽 상단',980,120],['수직흑화','왼쪽 하단',260,540],[selected.process,'선택된 공정',760,500]].map((x,i)=>`<article class="map-node ${i===4?'active':''}" style="left:${x[2]}px;top:${x[3]}px">${I('factory','lg')}<h3>${x[0]}</h3><p>${x[1]} · 작업자 인증</p></article>`).join('')}</main><footer class="map-foot"><span class="status">공정 지도</span><span class="grow"></span>${B('시험 시작','play','big')}</footer>`,

  () => `<header class="andon-head">${brand('OJT QUALITY ANDON')}<span class="grow"></span><span class="status">ALL SYSTEMS READY</span></header><main class="andon-grid"><article class="andon-cell good"><span>01 · 문제은행</span><div><h2>최신 상태</h2><p>시작할 때 자동 갱신 완료</p></div><span>OK</span></article><article class="andon-cell good active"><span>02 · 선택 시험</span><div><h2>${selected.process}</h2><p>${selected.desc}</p></div><span>SELECTED</span></article><article class="andon-cell good"><span>03 · 작업자</span><div><h2>오국진</h2><p>본인 확인 완료</p></div><span>VERIFIED</span></article><article class="andon-cell warn"><span>04 · 출력</span><div><h2>5 페이지</h2><p>문제 4 + 답안 1</p></div><span>READY</span></article><article class="andon-cell good"><span>05 · 총점</span><div><h2>100 점</h2><p>시험 조건 확인</p></div><span>OK</span></article><article class="andon-cell alert"><span>06 · 실행</span><div><h2>시험 시작</h2><p>모든 확인을 마쳤습니다.</p></div>${B('START','play','dark')}</article></main><footer class="andon-foot"><span>OJT 작업자 인증</span><span class="grow"></span><span>2026.08.06 · 08:42</span></footer>`,

  () => `<header class="handover-head">${brand('OJT SHIFT HANDOVER')}<span class="grow"></span><span class="status">주간조</span>${B('관리자','lock-keyhole','secondary')}</header><section class="shift-tabs">${[['sun','주간조','08:00–16:00'],['sunset','중간조','16:00–00:00'],['moon','야간조','00:00–08:00']].map((x,i)=>`<div class="shift-tab ${i===idx%3?'active':''}">${I(x[0],'lg')}<div><b>${x[1]}</b><p style="margin:4px 0 0;font-size:8px">${x[2]}</p></div></div>`).join('')}</section><main class="handover-body"><section class="handover-main">${heading('TODAY','이번 교대의 시험','완료되지 않은 시험을 먼저 표시합니다.')}<div>${processRows(8)}</div><div class="handover-note"><b>인수인계</b><p style="margin:7px 0 0;font-size:9px">PRESS 전장용 시험 1건이 남아 있습니다. 작업자 확인 후 진행하세요.</p></div></section><aside class="handover-side">${heading('NEXT',selected.process,'오국진 · 예정')}<div>${checks(5)}</div>${B('시험 시작','play','big')}</aside></main>`,

  () => `<header style="display:flex;align-items:center">${brand('OJT WEEK PLAN')}<span class="grow"></span>${B('오늘','calendar-days','secondary')}${B('관리자','lock-keyhole','secondary')}</header><main class="calendar-body"><section class="week"><div class="week-cell head">시간</div>${['월','화','수','목','금'].map(x=>`<div class="week-cell head">${x}</div>`).join('')}${Array.from({length:6},(_,r)=>`<div class="week-cell head">${8+r*2}:00</div>${Array.from({length:5},(_,c)=>`<div class="week-cell">${(r+c)%4===0?`<div class="event ${(r+c)%8===0?'active':''}">${['PRESS 일반용','TRIM 전장용','X-Ray 일반용'][r%3]}<br>${8+r*2}:30</div>`:''}</div>`).join('')}`).join('')}</section><aside class="calendar-side">${heading('TODAY','오늘의 다음 시험',selected.process)}<div>${identity()}<div style="margin-top:16px">${checks(4)}</div></div>${B('시험 시작','play','big')}</aside></main>`,

  () => `<header class="print-bar">${brand('OJT PRINT STUDIO')}<span class="grow"></span>${B('−','zoom-out','dark')}${B('100%','maximize-2','dark')}${B('+','zoom-in','dark')}${B('관리자','lock-keyhole','dark')}</header><main class="print-stage">${paper()}</main><footer class="print-dock">${B('이전 페이지','arrow-left','dark')}<span>1 / 5</span>${B('다음 페이지','arrow-right','dark')}<span class="grow"></span>${B('시험 다시 만들기','shuffle','dark')}${B('문제 + 답안 프린트','printer','big')}</footer>`,

  () => `<header class="compare-head">${brand('OJT DOCUMENT COMPARE')}<span class="grow"></span><span class="status">출력 비교</span>${B('관리자','lock-keyhole','secondary')}</header><main class="compare-body"><section class="compare-paper">${paper()}</section><aside class="compare-mid">${heading('COMPARE','미리보기 비교','왼쪽은 현재 문서, 오른쪽은 새 문서입니다.')}<div><div class="diff"><b>문제 순서</b><br>랜덤 배치됨</div><div class="diff" style="margin-top:10px"><b>시험 일자</b><br>2026.08.06</div><div class="diff" style="margin-top:10px"><b>총 페이지</b><br>5페이지</div></div>${B('새 문서 선택','check','secondary')}</aside><section class="compare-paper">${paper()}</section></main><footer class="compare-foot"><span class="status">A4 실제 비율</span><span class="grow"></span>${B('다시 만들기','shuffle','secondary')}${B('선택 문서 출력','printer','big')}</footer>`,

  () => `<header class="dock-head">${brand('OJT WORKBENCH')}<span class="grow"></span>${rolePills()}${B('관리자','lock-keyhole','secondary')}</header><main class="dock-main"><aside class="dock-panel">${heading('PROCESS','공정 선택',selected.name)}<div style="margin-top:16px">${processRows(8)}</div></aside><section class="dock-panel center">${I(selected.icon,'xl')}<span class="eyebrow">READY</span><h1>${selected.process}</h1><p style="color:#68777d">오국진 · 2026.08.06 · 100점</p>${B('시험 시작','play','huge')}</section><aside class="dock-panel">${heading('CHECK','시작 전 확인',selected.desc)}<div style="margin-top:16px">${identity()}</div><div style="margin-top:16px">${checks(5)}</div></aside></main><footer class="bottom-dock">${[['home','홈'],['factory','공정'],['play','시험'],['files','문서'],['history','기록'],['settings','설정']].map((x,i)=>`<button class="dock-action ${i===2?'active':''}">${I(x[0])}${x[1]}</button>`).join('')}</footer>`,

  () => `<header class="oneq-head">${brand('OJT ONE QUESTION')}<span class="grow"></span><span class="status">1 / 3</span>${B('관리자','lock-keyhole','secondary')}</header><main class="oneq-main"><h1>누가 시험을 보나요?</h1><section class="oneq-answers">${roles.map((r,i)=>`<article class="oneq-answer ${r.key===selected.key?'active':''}" style="${roleStyle(r)}"><span class="oneq-letter">${String.fromCharCode(65+i)}</span><div><h2>${r.name}</h2><p>${r.en}<br>${r.desc}</p></div><div style="display:flex;align-items:center"><span>${r.key===selected.key?'선택됨':'선택'}</span><span class="grow"></span>${I(r.icon,'lg')}</div></article>`).join('')}</section></main><footer class="oneq-foot"><span>한 번에 한 가지만 선택합니다.</span><span class="grow"></span>${B('다음','arrow-right','big')}</footer>`
];

function render(){
  themeKeys.forEach((key,i)=>app.style.setProperty(key,t[i]));
  app.className=`app v-${viewNames[idx]} ${idx%3===0?'flat':idx%3===1?'soft-buttons':''}`;
  app.innerHTML=builders[idx]()+`<span class="screen-id">${designNo} · ${concepts[idx][0]}</span>`;
  if(window.lucide)window.lucide.createIcons({'attrs':{'aria-hidden':'true'}});
}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
