const roles=[
  {key:'general',name:'일반용',en:'GENERAL',icon:'clipboard-list',color:'#008f7a',process:'PRESS 일반용',desc:'정기 작업자 인증'},
  {key:'electrical',name:'전장용',en:'ELECTRICAL',icon:'cpu',color:'#2f67d8',process:'PRESS 전장용',desc:'VDA 포함 인증'},
  {key:'newcomer',name:'신입용',en:'NEWCOMER',icon:'graduation-cap',color:'#5f9632',process:'액분석 신입용',desc:'교육 연계 인증'},
  {key:'foreigner',name:'외국인용',en:'GLOBAL',icon:'languages',color:'#c94c69',process:'PRESS 외국인용',desc:'다국어 인증'}
];

const concepts=[
  ['네 개의 시작 문','초간단','대상을 고르는 것부터 시작'],['한 버튼 시작','초간단','현재 선택을 확인하고 바로 시작'],['세 단계 작업대','초간단','세 칸을 왼쪽부터 순서대로 확인'],['대화형 안내','교육','질문에 답하며 시험 준비'],
  ['글로벌 체크인','글로벌','공항 체크인처럼 대상과 시험 확인'],['품질 안전 콘솔','현장','검증 상태를 먼저 확인하는 현장형'],['조용한 집중 화면','초간단','불필요한 장식을 줄인 한 화면'],['글로벌 타이포 그리드','글로벌','큰 글자와 선으로 빠르게 구분'],
  ['역할 기둥 작업대','운영','왼쪽 대상 선택과 중앙 업무 분리'],['준비 완료 화면','초간단','현재 시험만 크게 표시'],['종이 중심 스튜디오','문서','실제 출력물을 가장 크게 확인'],['페이지 덱','문서','출력 페이지를 카드처럼 넘겨 확인'],
  ['빠른 검색 콘솔','운영','공정명을 입력해 즉시 찾기'],['시험 생성 노선도','운영','현재 진행 단계를 노선처럼 확인'],['글로벌 안내 보드','글로벌','네 대상을 넓은 안내판으로 구분'],['큰 버튼 키오스크','현장','터치하기 쉬운 네 개의 큰 버튼'],
  ['간결한 품질 관제','관리','관리 정보는 모으고 작업은 단순하게'],['스마트 팩토리 맵','현장','공정 설비처럼 시험 대상을 표시'],['신입 학습 경로','교육','교육 진도와 시험을 한 흐름으로 연결'],['언어 우선 시작','글로벌','언어를 먼저 고르는 외국인용 구조'],
  ['작업자·관리자 분리','관리','작업 화면과 잠긴 설정을 명확히 분리'],['오늘의 시험 보드','운영','오늘 해야 할 시험만 먼저 표시'],['선택·문서 분할','문서','왼쪽 선택과 오른쪽 문서를 동시에 확인'],['설명 없는 3단계','초간단','번호 세 개만 따라가면 준비 완료']
];

const themes=[
  {bg:'#eef3f3',surface:'#fff',soft:'#dfe9e8',stage:'#ccd8da',ink:'#142126',muted:'#65777c',line:'#a7b8bb',accent:'#008f7a',a2:'#2f67d8',warm:'#e4a821'},
  {bg:'#f0f2f4',surface:'#fff',soft:'#e1e5e9',stage:'#d0d6dc',ink:'#17212e',muted:'#687483',line:'#aab4c0',accent:'#275dc7',a2:'#008f7a',warm:'#e39b24'},
  {bg:'#f4f1ed',surface:'#fff',soft:'#e9e2da',stage:'#dcd3ca',ink:'#241f1b',muted:'#766e65',line:'#bdb4aa',accent:'#b74d2e',a2:'#2368a7',warm:'#d69c1d'},
  {bg:'#edf1ee',surface:'#fff',soft:'#dde6df',stage:'#cfdacf',ink:'#17241b',muted:'#68756b',line:'#a9b7ac',accent:'#34754c',a2:'#2f67d8',warm:'#e0aa20'},
  {bg:'#eaf0f5',surface:'#fff',soft:'#d9e4ed',stage:'#c9d7e2',ink:'#17283a',muted:'#617487',line:'#a3b5c4',accent:'#125fa0',a2:'#008f7a',warm:'#f0a52c'},
  {bg:'#f2eff2',surface:'#fff',soft:'#e5dfe5',stage:'#d8d0d8',ink:'#282229',muted:'#746b75',line:'#b8aeba',accent:'#9b426b',a2:'#2f67d8',warm:'#d5a522'},
  {bg:'#f3f4f4',surface:'#fff',soft:'#e5e8e9',stage:'#d6dbdd',ink:'#171d20',muted:'#676f73',line:'#aeb8bc',accent:'#1f727c',a2:'#cc4d46',warm:'#e2a91c'},
  {bg:'#eff0ec',surface:'#fff',soft:'#e1e3dc',stage:'#d2d5cc',ink:'#22241e',muted:'#70736a',line:'#b3b7aa',accent:'#607c28',a2:'#2f67d8',warm:'#d49d1a'}
];

const q=new URLSearchParams(location.search);const designNo=Math.max(1,Math.min(24,Number(q.get('d')||1)));const idx=designNo-1;const app=document.getElementById('app');const theme=themes[idx%themes.length];const selected=roles[idx%4];
const I=(name,cls='')=>`<i data-lucide="${name}" class="icon ${cls}"></i>`;
const B=(label,icon='arrow-right',cls='')=>`<button class="btn ${cls}">${I(icon)}<span>${label}</span></button>`;
const brand=(label='OJT EXAM')=>`<div class="brand"><span class="brand-mark">${I('badge-check')}</span><div>${label} <b>MAKER</b><small>QUALITY TRAINING SYSTEM</small></div></div>`;
const workbook=()=>`<div class="workbook">${I('file-spreadsheet','sm')}<span>작업자 인증 시험 문제_20260805.xlsm</span><strong>최신</strong></div>`;
const roleStyle=r=>`--role:${r.color}`;
const rolePills=(active=selected.key)=>`<div class="role-pills">${roles.map(r=>`<button class="role-pill ${r.key===active?'active':''}" style="${roleStyle(r)}"><span class="role-dot"></span>${r.name}</button>`).join('')}</div>`;
const topbar=(opts={})=>`<header class="top ${opts.slim?'slim':''}">${brand(opts.label||'OJT EXAM')}<span class="grow"></span>${opts.workbook===false?'':workbook()}${opts.roles===false?'':rolePills()}${opts.actions===false?'':`<div class="actions">${B('파일','folder-open','secondary')}${B('관리자 설정','lock-keyhole','secondary')}</div>`}</header>`;
const heading=(eyebrow,title,copy='')=>`<div><span class="eyebrow">${eyebrow}</span><h1 class="title">${title}</h1>${copy?`<p class="copy">${copy}</p>`:''}</div>`;
const roleCards=(active=selected.key)=>`<div class="role-grid">${roles.map(r=>`<article class="role-card ${r.key===active?'active':''}" style="${roleStyle(r)}"><div class="role-icon">${I(r.icon)}</div><div><h3>${r.name}</h3><p>${r.en}<br>${r.desc}</p></div><small>${r.key===active?'선택됨':'선택'}</small></article>`).join('')}</div>`;
const identity=()=>`<div class="identity"><div class="field"><label>성명</label><div class="control"><span>오국진</span>${I('user-round','sm')}</div></div><div class="field"><label>평가 일시</label><div class="control"><span>2026.08.06</span>${I('calendar-days','sm')}</div></div></div>`;
const metrics=()=>`<div class="metric-strip"><div class="metric"><span>선택 시험</span><b>${selected.name}</b></div><div class="metric"><span>총점</span><b>100점</b></div><div class="metric"><span>문제은행</span><b>최신</b></div></div>`;
const checks=(count=5)=>`<div>${[['문제은행 연결','최신 파일 확인'],['공정별 문항','사용 가능'],['배점 합계','100점 확인'],['작업자 성명','입력 완료'],['출력 페이지','문제 + 답안']].slice(0,count).map(x=>`<div class="big-check"><span class="checkmark">✓</span><div><b>${x[0]}</b><small>${x[1]}</small></div><em>완료</em></div>`).join('')}</div>`;
const processRows=(limit=7)=>{const names=['PRESS 일반용','PRESS 전장용','액분석 신입용','PRESS 외국인용','TRIM 일반용','X-Ray 전장용','출하검사 일반용','수직흑화 신입용'];return `<div class="process-list">${names.slice(0,limit).map((n,i)=>`<div class="process-row ${i===idx%4?'active':''}"><span class="num">${i+1}</span><div><b>${n}</b><small>${i<4?roles[i].desc:'정기 인증 시험'}</small></div><em>${i===idx%4?'선택':'열기'}</em></div>`).join('')}</div>`};
function paper(large=false){const qs=['작업표준서와 실제 작업 방법이 다를 때 가장 적절한 조치는?','설비 점검 주기가 지났으나 생산 일정이 촉박하다. 어떻게 해야 하는가?','제품 표면의 조도 상태를 올바르게 판정한 것은?','현장 작업 중 이상 상태를 발견했을 때 가장 먼저 할 행동은?','최종 수세단 필터 교체 주기로 맞는 것은?'];return `<div class="paper ${large?'large':''}"><div class="paper-head"><div class="paper-grid"><span>부서명</span><span>가공팀</span><span>평가자</span><span>오국진</span><span>평가 일시</span><span>2026.08.06</span></div><div class="paper-title">교육 평가서</div><div class="approval"><span>기안</span><span>심의</span><span>결정</span><span></span><span></span><span></span><span>/</span><span>/</span><span>/</span></div></div><div class="paper-info"><span>직무명</span><span>${selected.process}</span><span>성명</span><span>오국진</span><span>평가 방법</span><span style="grid-column:2/5">시험 평가, 결과 보고서, 직무 평가</span><span>개정 차수</span><span>1</span><span>제정일</span><span>2026.08.06</span></div><div class="paper-qs">${qs.map((x,i)=>`<div class="paper-q"><b>${i+1}.</b><span>${x}</span><b>(${i<2?'2.5':'4'}점)</b><small>① 작업 중지　② 관리자 보고　③ 상태 기록　④ 기준 확인</small></div>`).join('')}</div><div class="paper-foot"><span>JIQP-0202-02</span><span>( 주 ) 지 인</span><span>A4(210*297)mm</span></div></div>`}
const pageCard=(active=false)=>`<div class="page-card ${active?'active':''}"><div class="page-lines">${Array.from({length:9},()=>'<div></div>').join('')}</div></div>`;
const lane=(r,active=false)=>`<article class="lane ${active?'active':''}" style="${roleStyle(r)}"><div class="lane-icon">${I(r.icon,'lg')}</div><div><h2>${r.name}</h2><p>${r.en}</p></div><div><b>${r.process}</b><p>${r.desc}</p></div>${I('arrow-right','lg')}</article>`;
const builders=[];

builders.push(
  () => `<div class="doors-head">${brand()}<span class="grow"></span>${workbook()}${B('관리자','lock-keyhole','secondary')}</div>${heading('START HERE','누가 시험을 보나요?','대상을 하나 선택하면 다음 단계로 이동합니다.')}<section class="doors-main">${roles.map(r=>`<article class="door" style="${roleStyle(r)}"><div class="role-icon">${I(r.icon,'lg')}</div><div><h2>${r.name}</h2><p>${r.en}<br>${r.desc}</p></div><div class="arrow">${I('arrow-right','lg')}</div></article>`).join('')}</section><footer class="doors-foot">${I('shield-check')}<b>문제은행 최신 파일 연결됨</b><span class="grow"></span><span>오늘 08:42 갱신</span></footer>`,

  () => `<aside class="one-side">${brand()}<div>${heading('CURRENT SELECTION',selected.name,selected.process)}<div style="margin-top:24px">${roleCards(selected.key)}</div></div><div class="lockbox">${I('lock-keyhole')}<div><b>관리자 설정</b><span>비밀번호로 보호됨</span></div></div></aside><main class="one-main"><div class="actions">${workbook()}<span class="grow"></span>${rolePills(selected.key)}</div><section class="one-center"><div class="role-icon" style="${roleStyle(selected)}">${I(selected.icon,'xl')}</div><span class="eyebrow">READY TO START</span><h1>${selected.process}</h1><p>오국진 · 2026.08.06 · 100점</p>${B('시험 시작','play','huge')}</section><footer class="one-footer"><div class="panel" style="padding:16px">${heading('01','대상 확인',selected.name)}</div><div class="panel" style="padding:16px">${heading('02','작업자 확인','오국진')}</div><div class="panel" style="padding:16px">${heading('03','출력','시험 종료 후')}</div></footer></main>`,

  () => `${topbar({actions:false})}<section>${heading('3 STEPS','세 가지만 확인하면 됩니다.','왼쪽부터 순서대로 확인하세요.')}</section><main class="three-main"><article class="three-pane"><div class="step-no">1</div><div><h2>시험 대상</h2>${roleCards(selected.key)}</div>${B('대상 확정','check','secondary')}</article><article class="three-pane active"><div class="step-no">2</div><div><h2>공정 선택</h2>${processRows(5)}</div>${B('공정 확정','check')}</article><article class="three-pane"><div class="step-no">3</div><div><h2>작업자 확인</h2><div style="margin-top:18px">${identity()}</div><div style="margin-top:18px">${checks(3)}</div></div>${B('시험 준비 완료','check-circle-2','secondary')}</article></main><footer class="actions"><span class="status ok">자동 저장</span><span class="grow"></span>${B('처음으로','rotate-ccw','secondary')}${B('시험 시작','play','big')}</footer>`,

  () => `<aside class="talk-side">${brand()}<div><div class="status ok">2 / 4 단계</div><h2 style="margin:18px 0 0">시험 준비</h2><p style="color:#b1c0c5;font-size:11px;line-height:1.7">대상을 확인한 다음<br>공정과 성명을 확인합니다.</p></div><div>${B('처음부터','rotate-ccw','secondary')}</div></aside><main class="talk-main"><section class="talk-bubble"><h1>어떤 시험을 준비할까요?</h1><p>아래에서 시험 대상을 하나 선택하세요.</p></section><section class="talk-options">${roles.map(r=>`<article class="talk-option ${r.key===selected.key?'active':''}" style="${roleStyle(r)}"><div class="role-icon">${I(r.icon)}</div><div><h2 style="margin:0">${r.name}</h2><p class="copy">${r.desc}</p></div>${r.key===selected.key?I('check-circle-2','lg'):I('chevron-right','lg')}</article>`).join('')}</section><footer class="actions"><span class="status ok">문제은행 연결됨</span><span class="grow"></span>${B('이전','arrow-left','secondary')}${B('다음','arrow-right','big')}</footer></main>`,

  () => `${topbar({label:'OJT CHECK-IN',roles:false})}<main class="airport-body"><aside class="airport-left">${heading('STEP 1','시험 대상','한 개를 선택하세요.')}<div>${roles.map(r=>`<div class="choice ${r.key===selected.key?'active':''}" style="${roleStyle(r)}">${I(r.icon)}<span>${r.name}</span><span class="grow"></span>${I('chevron-right')}</div>`).join('')}</div>${B('대상 변경','users-round','secondary')}</aside><section class="boarding"><div><span class="eyebrow" style="color:#7ed8c9">EXAM BOARDING PASS</span><h1>${selected.process}</h1></div><div class="boarding-code"><div class="code-cell"><span>WORKER</span><b>오국진</b></div><div class="code-cell"><span>DATE</span><b>2026.08.06</b></div><div class="code-cell"><span>QUESTIONS</span><b>24</b></div><div class="code-cell"><span>SCORE</span><b>100</b></div></div><div class="actions"><span class="status" style="color:#fff;border-color:#fff">READY</span><span class="grow"></span>${B('시험 시작','play','big')}</div></section><aside class="airport-right">${heading('STEP 2','출발 전 확인','모두 완료되어야 시작됩니다.')}<div>${checks(5)}</div>${B('확인 완료','check-circle-2','secondary')}</aside></main>`,

  () => `<header class="lab-head">${brand('OJT QUALITY')}<span class="grow"></span><span class="status ok">SYSTEM READY</span>${B('관리자','lock-keyhole','secondary')}</header><section class="lab-status"><div class="lab-cell ok"><span>문제은행</span><b>연결 정상</b></div><div class="lab-cell ok"><span>선택 대상</span><b>${selected.name}</b></div><div class="lab-cell ok"><span>작업자</span><b>오국진</b></div><div class="lab-cell ok"><span>총점</span><b>100점</b></div></section><main class="lab-main"><section class="lab-action"><div class="role-icon" style="${roleStyle(selected)}">${I(selected.icon,'xl')}</div><span style="color:#86a0a8">${selected.en}</span><h1>${selected.process}</h1>${B('인증 시험 시작','play','huge')}</section><aside class="lab-panel"><h2 style="margin:0 0 12px">출력 전 안전 확인</h2>${checks(5)}</aside></main><footer class="lab-head"><span>작업자 인증 시스템 · 품질관리</span><span class="grow"></span><span>2026.08.06 08:42</span></footer>`,

  () => `<header class="minimal-head" style="display:flex;align-items:center">${brand()}<span class="grow"></span>${rolePills(selected.key)}${B('설정','lock-keyhole','ghost')}</header><main class="quiet-main"><span class="eyebrow">ONE CLEAR CHOICE</span><h1>오늘은 어떤 시험을<br>시작할까요?</h1><p>대상과 공정을 선택한 뒤 시작 버튼만 누르면 됩니다.</p><div style="margin-top:28px">${B('선택한 시험 시작','play','huge')}</div></main><section class="quiet-roles">${roles.map(r=>`<article class="quiet-role ${r.key===selected.key?'active':''}" style="${roleStyle(r)}"><div class="role-icon">${I(r.icon)}</div><div><b>${r.name}</b><p class="copy">${r.process}</p></div></article>`).join('')}</section>`,

  () => `<div class="swiss-number">01</div><div class="swiss-title"><span>OJT EXAM MAKER</span><h1>SELECT<br>YOUR EXAM</h1></div><main class="swiss-board">${roles.map((r,i)=>`<article class="swiss-role ${r.key===selected.key?'active':''}"><small>0${i+1} / ${r.en}</small><div><h2>${r.name}</h2><p>${r.process}</p></div><span>${r.key===selected.key?'SELECTED':'OPEN →'}</span></article>`).join('')}</main><footer class="swiss-foot"><b>작업자 인증 시험</b><span class="grow"></span><span>오국진 · 2026.08.06</span>${B('CONTINUE','arrow-right','big')}</footer>`
);

builders.push(
  () => `<header class="top slim">${brand('OJT CONTROL')}<span class="grow"></span>${workbook()}${rolePills(selected.key)}${B('설정','lock-keyhole','secondary')}</header><div class="control-body"><aside class="control-nav">${[['home','홈'],['play','시험 시작'],['factory','공정'],['file-text','시험지'],['history','출력 이력'],['settings','관리자 설정']].map((x,i)=>`<div class="navitem ${i===1?'active':''}">${I(x[0])}<span>${x[1]}</span></div>`).join('')}<span class="grow"></span><div class="navitem">${I('log-out')}<span>종료</span></div></aside><main class="control-main"><section class="panel" style="padding:16px">${metrics()}</section><section class="panel">${processRows(8)}</section></main><aside class="control-right">${heading('READY','시험 준비',selected.process)}<div>${identity()}<div style="margin-top:14px">${checks(5)}</div></div>${B('시험 시작','play','big')}</aside></div>`,

  () => `<header class="actions">${brand('OJT FACTORY')}<span class="grow"></span><span class="status ok">ALL SYSTEMS NORMAL</span>${B('관리자','lock-keyhole','secondary')}</header><main class="factory-map">${roles.map((r,i)=>`<article class="factory-line ${r.key===selected.key?'active':''}" style="${roleStyle(r)}"><div class="actions"><span class="status">LINE 0${i+1}</span><span class="grow"></span><span>${r.en}</span></div><div class="machine"><div class="machine-box">${I(r.icon,'xl')}</div><h2>${r.name}</h2><p style="color:#aab8bd">${r.process}</p></div><div class="actions"><span>${r.key===selected.key?'선택됨':'대기'}</span><span class="grow"></span>${I('arrow-right')}</div></article>`).join('')}</main><footer class="factory-foot"><span class="status ok">작업자 확인</span><b>오국진</b><span class="grow"></span><span>${selected.process} · 100점</span>${B('시험 시작','play','big')}</footer>`,

  () => `<header class="actions">${brand('OJT LEARNING')}<span class="grow"></span><span class="status ok">신입 교육 80%</span>${B('관리자','lock-keyhole','secondary')}</header><section class="learning-path">${[['book-open','기초 교육'],['shield-check','안전 교육'],['factory','공정 실습'],['clipboard-check','확인 시험'],['award','인증 완료']].map((x,i)=>`<div class="learn-step ${i<3?'done':''}"><div class="learn-dot">${I(x[0],'lg')}</div><b>${x[1]}</b><span class="copy">${i<3?'완료':'다음'}</span></div>`).join('')}</section><main class="learning-main"><section class="panel" style="padding:22px;display:grid;grid-template-rows:auto 1fr auto;gap:16px">${heading('NEXT STEP','확인 시험을 준비합니다.','교육 내용을 이해했는지 확인하는 시험입니다.')}<div>${processRows(6)}</div><div class="actions"><span class="status ok">교육 이수 확인됨</span><span class="grow"></span>${B('확인 시험 시작','play','big')}</div></section><aside class="panel" style="padding:18px">${heading('LEARNER','작업자 정보','신입용 인증')}<div style="margin-top:18px">${identity()}</div><div style="margin-top:18px">${checks(4)}</div></aside></main><footer class="actions"><span>도움이 필요하면 관리자에게 문의하세요.</span><span class="grow"></span>${B('교육 내용 다시 보기','book-open','secondary')}</footer>`,

  () => `<header class="actions">${brand('OJT GLOBAL')}<span class="grow"></span>${workbook()}${B('관리자','lock-keyhole','secondary')}</header><section>${heading('CHOOSE LANGUAGE','사용할 언어를 선택하세요.','Select your language / Chọn ngôn ngữ / 请选择语言')}</section><div class="language-grid">${[['KR','한국어'],['EN','English'],['VI','Tiếng Việt'],['CN','中文']].map((x,i)=>`<article class="language ${i===idx%4?'active':''}"><b>${x[0]}</b><span>${x[1]}</span></article>`).join('')}</div><main class="language-main"><section class="language-preview"><span class="eyebrow">KOREAN</span><h2>${selected.process}</h2><p>시험 대상과 작업자 정보를 확인한 뒤 시험을 시작합니다.<br>문제와 답안지는 마지막에 함께 출력됩니다.</p></section><section class="language-preview"><span class="eyebrow">ENGLISH</span><h2>${selected.en} EXAM</h2><p>Confirm the exam type and worker name before starting.<br>The exam and answer sheet print together at the end.</p></section></main><footer class="actions"><span class="status ok">Language ready</span><span class="grow"></span>${B('Back','arrow-left','secondary')}${B('Continue','arrow-right','big')}</footer>`,

  () => `<main class="worker-main"><header class="actions">${brand()}<span class="grow"></span>${rolePills(selected.key)}</header><section class="worker-start"><div class="role-icon" style="${roleStyle(selected)}">${I(selected.icon,'xl')}</div><span class="eyebrow">WORKER MODE</span><h1>${selected.process}</h1><p class="copy">오국진 · 2026.08.06</p>${B('시험 시작','play','huge')}</section><footer class="one-footer"><div class="panel" style="padding:15px">${heading('대상',selected.name)}</div><div class="panel" style="padding:15px">${heading('문항','24개')}</div><div class="panel" style="padding:15px">${heading('총점','100점')}</div></footer></main><aside class="super-side">${brand('SUPERVISOR')}<div><h2>관리자 영역</h2><p style="color:#aebcc1;font-size:11px;line-height:1.7">시험 설정과 문제 구성은<br>비밀번호로 보호됩니다.</p><div style="margin-top:22px">${[['settings','시험 설정'],['database','문제은행'],['printer','출력 관리'],['history','작업 이력']].map(x=>`<div class="lockbox">${I(x[0])}<div><b>${x[1]}</b><span>잠김</span></div><span class="grow"></span>${I('lock','sm')}</div>`).join('')}</div></div>${B('비밀번호 입력','key-round','secondary')}</aside>`,

  () => `<header class="actions">${brand('OJT TODAY')}<span class="grow"></span><span class="status ok">2026.08.06 목요일</span>${B('관리자','lock-keyhole','secondary')}</header><main class="today-body"><section class="today-main">${heading('TODAY','오늘 예정된 시험','현재 시간 기준으로 필요한 시험을 먼저 보여줍니다.')}<div class="schedule">${[['08:30','PRESS 일반용','완료'],['10:00',selected.process,'지금'],['13:30','TRIM 전장용','대기'],['15:00','액분석 신입용','대기'],['16:30','출하검사 일반용','대기']].map((x,i)=>`<div class="schedule-row ${i===1?'active':''}"><time>${x[0]}</time><div><b>${x[1]}</b><small>${i===1?'오국진 · 준비 완료':'정기 작업자 인증'}</small></div><span class="status ${i===1?'ok':''}">${x[2]}</span></div>`).join('')}</div></section><aside class="today-focus"><div><span class="eyebrow" style="color:#7ddbc9">NOW</span><h1>${selected.process}</h1></div><div style="align-self:center">${identity()}<div style="margin-top:16px">${checks(4)}</div></div><div class="actions"><span class="status" style="color:#fff;border-color:#fff">준비 완료</span><span class="grow"></span>${B('시작','play','big')}</div></aside></main>`,

  () => `<aside class="split-left">${brand()}${heading('SELECT',selected.name,selected.process)}<div><h3>시험 대상</h3>${roles.map(r=>`<div class="choice ${r.key===selected.key?'active':''}" style="${roleStyle(r)}">${I(r.icon)}<span>${r.name}</span></div>`).join('')}<h3 style="margin-top:22px">작업자</h3>${identity()}</div>${B('선택 확정','check-circle-2','secondary')}</aside><main class="split-right"><header class="top slim">${heading('DOCUMENT','출력 문서')}<span class="grow"></span>${B('전체 페이지','files','secondary')}</header><section class="split-stage"><div class="paper-stage">${paper(true)}</div><aside class="split-info">${heading('READY','인쇄 준비','문제 4페이지 + 답안 1페이지')}<div>${checks(5)}</div>${B('시험 시작','play','big')}</aside></section><footer class="split-foot"><span class="status ok">실제 A4 비율</span><span class="grow"></span>${B('출력 미리보기','scan-search','secondary')}${B('문제 + 답안 출력','printer')}</footer></main>`,

  () => `<header class="actions">${brand('OJT SIMPLE')}<span class="grow"></span>${workbook()}${B('관리자','lock-keyhole','secondary')}</header><main class="zero-main"><section class="zero-band"><span class="zero-no">1</span><div><h2>시험 대상</h2><p>누가 시험을 보는지 선택</p></div>${rolePills(selected.key)}${I('check-circle-2','lg')}</section><section class="zero-band active"><span class="zero-no">2</span><div><h2>공정</h2><p>시험 볼 공정 하나 선택</p></div><div class="control">${selected.process}<span class="grow"></span>${I('chevron-down')}</div>${I('check-circle-2','lg')}</section><section class="zero-band"><span class="zero-no">3</span><div><h2>성명</h2><p>작업자 이름과 날짜 확인</p></div><div style="min-width:520px">${identity()}</div>${I('check-circle-2','lg')}</section></main><footer class="zero-foot"><span class="status ok">세 단계 확인 완료</span><span class="grow"></span>${B('처음부터','rotate-ccw','secondary')}${B('시험 시작','play','huge')}</footer>`
);

window.addEventListener('DOMContentLoaded',()=>{
  const ordered=[...builders.slice(0,8),...builders.slice(16,24),...builders.slice(8,16)];
  builders.splice(0,builders.length,...ordered);
  const viewNames=['doors','one','three','talk','airport','lab','quiet','swiss','pillar','start','paper','deck','search','flow','sign','kiosk','control','factory','learning','language','supervisor','today','split','zero'];
  const buttonStyles=['button-edge','button-tactile','button-soft','button-flat','button-outline','button-edge','button-soft','button-flat'];
  Object.entries({'--bg':theme.bg,'--surface':theme.surface,'--soft':theme.soft,'--stage':theme.stage,'--ink':theme.ink,'--muted':theme.muted,'--line':theme.line,'--accent':theme.accent,'--accent2':theme.a2,'--warm':theme.warm}).forEach(([k,v])=>app.style.setProperty(k,v));
  app.className=`app view-${viewNames[idx]} ${buttonStyles[idx%buttonStyles.length]}`;
  app.innerHTML=builders[idx]()+`<span class="screen-id">${String(designNo).padStart(2,'0')} · ${concepts[idx][0]}</span>`;
  if(window.lucide)window.lucide.createIcons({'attrs':{'aria-hidden':'true'}});
});

builders.push(
  () => `<aside class="pillar-side">${brand()}<div class="pillar-roles">${roles.map(r=>`<div class="pillar-role ${r.key===selected.key?'active':''}" style="${roleStyle(r)}">${I(r.icon)}<span>${r.name}</span></div>`).join('')}</div><div class="lockbox">${I('lock-keyhole')}<div><b>관리자 설정</b><span>비밀번호 필요</span></div></div></aside><main class="pillar-main"><header class="actions">${heading('WORKSPACE',selected.process,'오국진 · 2026.08.06')}<span class="grow"></span>${workbook()}</header><section class="paper-stage">${paper(true)}</section><footer class="actions">${B('공정 변경','factory','secondary')}<span class="grow"></span>${B('출력 미리보기','scan-search','secondary')}${B('시험 시작','play','big')}</footer></main><aside class="pillar-summary">${heading('READY','준비 완료','필수 항목을 모두 확인했습니다.')}<div>${identity()}</div><div>${checks(5)}</div>${B('문제 + 답안 출력','printer','secondary')}</aside>`,

  () => `<header class="actions">${brand()}<span class="grow"></span>${workbook()}${B('관리자','lock-keyhole','secondary')}</header><section class="start-progress">${[['check','대상 선택'],['check','공정 선택'],['check','성명 확인'],['play','시험 시작']].map((x,i)=>`<div class="progress-step ${i<3?'done':''}">${I(x[0])}<span>${i+1}. ${x[1]}</span></div>`).join('')}</section><main class="start-center"><div class="role-icon" style="${roleStyle(selected)}">${I(selected.icon,'xl')}</div><span class="eyebrow">ALL SET</span><h1>${selected.process}</h1><p class="copy">${selected.name} · 오국진 · 2026.08.06 · 100점</p>${B('지금 시험 시작','play','huge')}</main><footer class="actions"><span class="status ok">자동 검증 완료</span><span class="grow"></span>${B('처음부터 다시 선택','rotate-ccw','secondary')}</footer>`,

  () => `<aside class="paper-tools">${[['folder-open','파일'],['zoom-in','확대'],['zoom-out','축소'],['files','페이지'],['printer','출력'],['settings','설정']].map(x=>`<button class="btn secondary" title="${x[1]}">${I(x[0])}</button>`).join('')}</aside><main class="paper-work">${paper(true)}</main><aside class="paper-side">${heading('PRINT PREVIEW','실제 출력 모습','A4 세로 · 문제 4페이지 + 답안 1페이지')}<div class="actions">${B('−','zoom-out','secondary')}${B('100%','maximize-2','secondary')}${B('+','zoom-in','secondary')}</div><div>${identity()}<div style="margin-top:14px">${checks(4)}</div></div>${B('문제 + 답안 프린트','printer','big')}</aside>`,

  () => `${topbar({slim:true,actions:false})}<main class="deck-main"><section class="deck-stage"><div class="page-deck">${[0,1,2,3,4].map(i=>pageCard(i===1)).join('')}</div></section><aside class="deck-side">${heading('5 PAGES','출력 페이지','선택한 페이지를 크게 확인합니다.')}<div>${[['01','표지 + 문제'],['02','문제'],['03','문제'],['04','문제'],['05','답안지']].map((x,i)=>`<div class="process-row ${i===1?'active':''}"><span class="num">${x[0]}</span><div><b>${x[1]}</b><small>${i===4?'채점란 포함':'A4 세로'}</small></div><em>보기</em></div>`).join('')}</div>${B('선택 페이지 확대','maximize-2','secondary')}</aside></main><footer class="deck-foot"><span class="status ok">문서 생성 완료</span><span class="grow"></span>${B('시험 다시 만들기','shuffle','secondary')}${B('전체 페이지 출력','printer','big')}</footer>`,

  () => `<header class="actions">${brand('OJT FIND')}<span class="grow"></span>${rolePills(selected.key)}${B('관리자','lock-keyhole','secondary')}</header><section>${heading('QUICK FIND','무슨 공정 시험이 필요한가요?','공정명 한 단어만 입력해도 됩니다.')}</section><div class="searchbar">${I('search','lg')}<input value="PRESS" aria-label="공정 검색"><span class="status ok">8개 결과</span></div><main class="search-results"><section class="result-main">${processRows(8)}</section><aside class="result-side">${heading('SELECTED',selected.process,selected.desc)}${metrics()}<div>${identity()}<div style="margin-top:14px">${checks(3)}</div></div>${B('이 시험 시작','play','big')}</aside></main><footer class="actions"><span>최근 검색: TRIM · X-Ray · 출하검사</span><span class="grow"></span>${B('전체 공정 보기','rows-3','secondary')}</footer>`,

  () => `<header class="actions">${brand('OJT ROUTE')}<span class="grow"></span>${rolePills(selected.key)}${B('설정','lock-keyhole','secondary')}</header><main class="flow-main"><div class="flow">${[['users-round','대상','일반용'],['factory','공정',selected.process],['user-round','작업자','오국진'],['play','시작','준비 완료']].map((x,i)=>`<article class="flow-node ${i===1?'active':''}">${I(x[0],'lg')}<b>${i+1}. ${x[1]}</b><span>${x[2]}</span></article>`).join('')}</div></main><footer class="flow-foot"><div class="prompt"><div class="prompt-icon">${I('factory','lg')}</div><div><h2>${selected.process}</h2><p>${selected.desc} · 문제은행 확인 완료</p></div></div><div class="actions" style="justify-content:flex-end">${B('이전','arrow-left','secondary')}${B('다음','arrow-right','big')}</div></footer>`,

  () => `<header class="actions">${brand('OJT GLOBAL')}<span class="grow"></span>${workbook()}${B('관리자','lock-keyhole','secondary')}</header><main class="sign-lanes">${roles.map(r=>lane(r,r.key===selected.key)).join('')}</main><footer class="sign-foot">${I('mouse-pointer-click')}<b>${selected.name} 선택됨</b><span class="grow"></span><span>${selected.process}</span>${B('계속','arrow-right','big')}</footer>`,

  () => `<header class="kiosk-head">${brand('OJT STATION')}<span class="grow"></span><span class="status ok">문제은행 최신</span>${B('관리자','lock-keyhole','secondary')}</header><main class="kiosk-grid">${roles.map(r=>`<article class="kiosk-card ${r.key===selected.key?'active':''}" style="${roleStyle(r)}"><div class="role-icon">${I(r.icon,'lg')}</div><div><h2>${r.name}</h2><p>${r.en}<br>${r.desc}</p></div>${I('chevron-right','lg')}</article>`).join('')}</main><footer class="kiosk-foot">${I('hand')}<b>시험 대상을 선택하세요.</b><span class="grow"></span><span>오국진 · 2026.08.06</span></footer>`
);
